
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ieujbcdoxautagaebhpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlldWpiY2RveGF1dGFnYWViaHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDM2ODIsImV4cCI6MjA2MDQ3OTY4Mn0.aaajjBPLMW_Ww1aogkEVSzDe8ubXYfkKr6r3ZMVuyOs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
